version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: finance-visualizer-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: finance-visualizer
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
